### ISSUE TITLE
EOSC Life reporting

### ISSUE THREAD

**Issue by pherterich** [open-life-science/resident-fellowship-patricia#3]
- [x] Double check contract
- [x] Create spreadsheet covering main metadata (incl. institution as there is a max. for individual institutions)
- [x] Go through past cohorts and add relevant participants
- [x] Figure out ways to target institutions for the last round - NOT NEEDED
- [x] Report back to EOSC-Life and send invoice

**Comment by pazbc** [comment]
Hallo!!  :)

**Comment by pherterich** [comment]
Now with Emmy for final finances
